### ISSUE TITLE
Work in devel branch

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/rstudio-server-launcher#1]
@hgputnam. FYI, I've been doing quite a bit of work over in the devel branch. I'm not done, so haven't merged yet.

**Comment by hgputnam** [comment]
Oh OK, should I stop what I am doing? I think I have at least started to zero  in on what needs to be fixed with the pam-helper thing.

**Comment by HenrikBengtsson** [comment]
You can keep working. It's not a giant script, so if automatic merging doesn't work, we can always do it manually.  Just wanted to let you know.

**Comment by HenrikBengtsson** [comment]
I've merged my current work into the main branch.

The new script comes with a few improvements:

* A lock file prevents a user from launching more than one instance on the cluster
* It validates that `R`, `rserver`, `rsession`, and `pam-helper` is on the `PATH` before attempting to launch the RStudio Server.
* It uses `module load CBI rstudio-server`, which is built from source and to which I've added a custom `pam-helper` tool.
* It uses `~/.config/rstudio-server-launcher/` instead of ``~/rstudio-server/`
* One can override `LOCALPORT` and `RSTUDIO_PORT`, by setting those environment variables.
* For troubleshooting/development purposes, one can also override `RSTUDIO_PASSWORD` and `RSTUDIO_USER`.  However, we might wanna undo this for `RSTUDIO_PASSWORD`, so that users don't start using a static password all the time.
* You can troubleshoot the `pam-helper` input by setting `PAM_HELPER_LOGFILE` and inspecting that file later on.
